### router user
GET http://localhost:3001/user/allUsers

###

POST http://localhost:3001/user/inscription
Content-Type: application/json

{
  "name": "JulienDevWeb",
  "password": "Louislucie1997.",
  "email": "pierratlabollejulien@gmail.com"

}

###

POST http://localhost:3001/user/connexion

Content-Type: application/json

{
  "name": "user1",
  "password": "Louislucie1997."
}

### supprimer un user

DELETE http://localhost:3001/user/delete/53
Content-Type: application/json

{
  "password": "Louislucie1997."
}

### mise à jour d'un user en admin

PUT http://localhost:3001/user/changerole/1
Content-Type: application/json

{
    "role": "admin"
}

### essayer de se connecter

POST http://localhost:3001/user/connexion
Content-Type: application/json

{
  "name": "user",
  "password": "Louislucie1997."
}


